"""Official TPC-H QphH@Size evaluator (pure function over the official.json artifact).

Maps the phase-machine output (``official.json``: Load / Power / Throughput / ACID)
into namespaced ``tpc-h.*`` :class:`Measurement` objects using the official TPC-H
formulas (:mod:`clousight_bench.suites._tpc_official.metrics`). Registered as
``official-tpch-qphh-evaluator`` — the ``mode: official`` companion to the existing
``official-tpch-evaluator`` (reference path).

Every score carries ``official=True`` as a *provenance flag* (this is the suite's
official evaluator), NOT an audit claim: the composites note ``unaudited`` and that
the refresh set is clousight-generated. Timing-derived scores are ``environmental``;
ACID pass/fail is ``deterministic``. Any missing/malformed section omits only the
affected dimension — the evaluator never raises.

Deliberately NO answer-correctness dimension here: the official Power test runs
its queries AFTER RF1 has refreshed the data, so results legitimately differ
from the pristine-data references — comparing them would mislabel correct
behavior as failure. Correctness (verified against DuckDB's official answers)
rides the ``reference`` mode, whose queries run on pristine data.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from clousight_bench.core.observation import Measurement
from clousight_bench.core.suite import Evaluator, RawArtifacts
from clousight_bench.suites._tpc_official import metrics

_FIXTURES_DIR = Path(__file__).parent / "fixtures"
_UNAUDITED = "official TPC-H QphH formula; unaudited; refresh-set generated by clousight"


class OfficialTpchQphhEvaluator(Evaluator):
    """Evaluate a ``mode: official`` TPC-H run's ``official.json`` into QphH measurements."""

    evaluator_id = "official-tpch-qphh-evaluator"
    official = True
    fixtures_dir: Path = _FIXTURES_DIR

    def supports(self, suite_id: str, product: str) -> bool:  # noqa: ARG002
        return suite_id == "tpc-h"

    def evaluate(self, raw: RawArtifacts) -> dict[str, Measurement]:
        try:
            doc: dict[str, Any] = json.loads(raw.path("official").read_text())
        except Exception:  # noqa: BLE001 - no/broken official.json → nothing to score
            return {}
        if not isinstance(doc, dict):
            return {}

        out: dict[str, Measurement] = {}
        sf = _as_float(doc.get("scale_factor"))

        self._add_load(out, doc)
        self._add_power_and_composite(out, doc, sf)
        self._add_acid(out, doc)
        return out

    # ---------------------------------------------------------------- load
    def _add_load(self, out: dict[str, Measurement], doc: dict[str, Any]) -> None:
        load_s = _as_float((doc.get("load") or {}).get("load_time_s"))
        if load_s is not None:
            out["tpc-h.load_time_s"] = Measurement(
                value=load_s, unit="s", reproducibility_class="environmental", official=True
            )

    # ------------------------------------------------- power + throughput + qphh
    def _add_power_and_composite(
        self, out: dict[str, Measurement], doc: dict[str, Any], sf: float | None
    ) -> bool:
        power = doc.get("power")
        if not isinstance(power, dict) or sf is None:
            return False
        queries = power.get("queries")
        if not isinstance(queries, list) or not queries:
            return False
        try:
            qi = [float(q["interval_s"]) for q in queries]
            ri = [float(power["rf1_s"]), float(power["rf2_s"])]
        except (KeyError, TypeError, ValueError):
            return False

        try:
            power_val = metrics.power_at_size(qi, ri, scale_factor=sf)
        except ValueError:
            return False
        out["tpc-h.power_at_size"] = Measurement(
            value=power_val,
            unit="QphH",
            reproducibility_class="environmental",
            official=True,
            notes=_UNAUDITED,
        )

        tp = doc.get("throughput")
        if isinstance(tp, dict):
            streams = tp.get("query_streams")
            elapsed = _as_float(tp.get("elapsed_s"))
            if isinstance(streams, list) and streams and elapsed is not None:
                s = len(streams)
                q = len(streams[0].get("queries", [])) or len(queries)
                try:
                    tput_val = metrics.throughput_at_size(
                        num_streams=s, num_queries=q, elapsed_s=elapsed, scale_factor=sf
                    )
                except ValueError:
                    tput_val = None
                if tput_val is not None:
                    out["tpc-h.throughput_at_size"] = Measurement(
                        value=tput_val,
                        unit="QphH",
                        reproducibility_class="environmental",
                        official=True,
                        notes=_UNAUDITED,
                    )
                    out["tpc-h.qphh_at_size"] = Measurement(
                        value=metrics.qphh_at_size(power_val, tput_val),
                        unit="QphH",
                        reproducibility_class="environmental",
                        official=True,
                        notes=_UNAUDITED,
                    )
        return True

    # --------------------------------------------------------------- ACID gate
    def _add_acid(self, out: dict[str, Measurement], doc: dict[str, Any]) -> None:
        acid = doc.get("acid")
        if not isinstance(acid, dict):
            return
        note = "best-effort adaptation of TPC-H ACID tests; unaudited"
        for name in ("atomicity", "consistency", "isolation"):
            verdict = acid.get(name)
            if verdict in ("pass", "fail"):
                out[f"tpc-h.acid_{name}"] = Measurement(
                    value=1.0 if verdict == "pass" else 0.0,
                    unit="pass",
                    reproducibility_class="deterministic",
                    official=True,
                    notes=note,
                )
        # durability is n/a on embedded DuckDB → intentionally omitted (see notes elsewhere)


def _as_float(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None
