#!/usr/bin/env python
"""Regenerate the machine-derived blocks in ``docs/architecture.mdx``.

The task inventory and adapter-status table drift the moment a task is added,
renamed or an adapter changes status. Rather than hand-maintain those facts (and
silently get them wrong — e.g. a stale "28 tasks"), we generate them from the
same source ``csbench list --json`` uses: :func:`clousight_bench.core.inventory.inventory`.

Usage::

    python scripts/gen_docs.py            # rewrite docs in place
    python scripts/gen_docs.py --check    # exit 1 if docs are stale (CI gate)

The generated span lives between the markers::

    <!-- BEGIN generated:task-inventory -->
    ...
    <!-- END generated:task-inventory -->

Everything outside the markers is hand-written prose and is never touched.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Allow running as a plain script (python scripts/gen_docs.py) without install.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from clousight_bench.core.inventory import inventory  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
# The task-inventory block is mirrored into every language's architecture page.
# Its content stays English (registry reference data) in all of them.
ARCHITECTURE_DOCS = [
    REPO_ROOT / "docs" / "architecture.mdx",
    REPO_ROOT / "docs" / "zh" / "architecture.mdx",
]

# MDX (Mintlify) rejects HTML `<!-- -->` comments; use JSX `{/* */}` comments so
# architecture.mdx stays valid MDX. The splice logic is marker-agnostic.
BEGIN_MARKER = "{/* BEGIN generated:task-inventory */}"
END_MARKER = "{/* END generated:task-inventory */}"

_DO_NOT_EDIT = (
    "{/* Generated by scripts/gen_docs.py from the domain registry "
    "(same source as `csbench list --json`). Do not edit by hand; run "
    "`python scripts/gen_docs.py`. */}"
)


def _task_sort_key(task_id: str) -> tuple:
    """Natural order so T1.2 sorts before T1.10 (string sort would not)."""
    return tuple(int(p) if p.isdigit() else p for p in re.split(r"(\d+)", task_id))


def _plural(n: int, noun: str) -> str:
    return f"{n} {noun}" if n == 1 else f"{n} {noun}s"


def render_inventory(payload: dict) -> str:
    """Render the inventory payload to the markdown that lives between markers.

    Deterministic: domains come sorted from :func:`inventory`, tasks are
    natural-sorted here, adapters keep the payload's sorted order.
    """
    lines: list[str] = [_DO_NOT_EDIT, ""]
    for domain in payload["domains"]:
        tasks = sorted(domain["tasks"], key=lambda t: _task_sort_key(t["task_id"]))
        lines.append(f"### `{domain['domain']}` — {_plural(len(tasks), 'task')}")
        lines.append("")
        lines.append("| Task | Title | Evidence |")
        lines.append("|---|---|---|")
        for t in tasks:
            lines.append(f"| {t['task_id']} | {t['title']} | {t['evidence_layer']} |")
        lines.append("")
        platforms = domain["platforms"]
        if platforms:
            rendered = " · ".join(f"`{p['platform']}` {p['status']}" for p in platforms)
            lines.append(f"**Adapters:** {rendered}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _splice(doc: str, inner: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(doc):
        raise SystemExit(
            f"markers {BEGIN_MARKER} / {END_MARKER} not found in the doc — "
            "add them once where the generated block should live."
        )
    replacement = f"{BEGIN_MARKER}\n{inner}{END_MARKER}"
    return pattern.sub(lambda _m: replacement, doc, count=1)


def build_doc(current: str, payload: dict | None = None) -> str:
    """Return ``current`` with the generated span replaced by fresh content."""
    payload = payload if payload is not None else inventory()
    return _splice(current, render_inventory(payload))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 (without writing) if the doc is stale",
    )
    args = ap.parse_args(argv)

    rc = 0
    for doc_path in ARCHITECTURE_DOCS:
        rel = doc_path.relative_to(REPO_ROOT)
        current = doc_path.read_text(encoding="utf-8")
        updated = build_doc(current)
        if current == updated:
            print(f"{rel}: up to date")
            continue
        if args.check:
            print(
                f"{rel}: STALE — run `python scripts/gen_docs.py` to regenerate the task-inventory block.",
                file=sys.stderr,
            )
            rc = 1
            continue
        doc_path.write_text(updated, encoding="utf-8")
        print(f"{rel}: regenerated")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
